export const kutnaHora = [
  {
    name: "Chrám Sv. Barbory",
    tag: ["church", "history"],
    latitude: 49.944939,
    longitude: 15.263566,
    outputName: "Chrám Sv. Barbory",
    outputAddress: "Barborská, 284 01 Kutná Hora",
    outputDescription: "Památka UNESCO, klenot pozdní gotiky a jedna ze čtyř staveb katedrálního typu v Čechách.",

  },
  {
    name: "Katedrála Nanebevzetí Panny Marie a svatého Jana Křtitele",
    tag: ["church", "history"],
    latitude: 49.944939,
    longitude: 15.263566,
    outputName: "Katedrála Nanebevzetí Panny Marie a svatého Jana Křtitele",
    outputAddress: "U Zastávky 280, Sedlec, 284 03 Kutná Hora",
    outputDescription: "Památka UNESCO od roku 1995 je koncentním chrámem bývalého nejstaršího cisterciáckého opátství v Čechách.",
  },
  {
    name: "Alchymistická dílna",
    tag: ["museum", "history", "kids"],
    latitude: 49.949815,
    longitude: 15.268534,
    outputName: "Alchymistická dílna",
    outputAddress: "Palackého nám. 377, Vnitřní Město, 284 01 Kutná Hora",
    outputDescription: "Zavede Vás do 15. století, kdy věhlasní učenci se svými pomocníky hledali kámen mudrců a bádali, kterak změnit kovy ve zlato.",
  },
  {
    name: "Muzeum čokolády a čokoládovna Kutná Hora",
    tag: ["museum", "kids"],
    latitude: 49.948845,
    longitude: 15.265830,
    outputName: "Muzeum čokolády a čokoládovna Kutná Hora",
    outputAddress: "Komenského nám. 72, 284 01 Kutná Hora",
    outputDescription: "Malé muzeum místní čokoládovny Koukol & Michera, ktorá pod značkou Lidka vyvážela čokolády do celého světa.",
  },
  {
    name: "Bobová a motokárová dráha",
    tag: ["sport", "fun", "kids"],
    latitude: 49.946416,
    longitude: 15.276156,
    outputName: "Bobová a motokárová dráha",
    outputAddress: "Čáslavská 274, 284 01 Kutná Hora",
    outputDescription: "Dráha je unikátně položena na třech svazích a svou délkou 1565 m je nejdelší v České republice a druhá nejdelší v Evropě.",
  },
  {
    name: "Solná jeskyně",
    tag: ["relax", "health"],
    latitude: 49.947398,
    longitude: 15.287073,
    outputName: "Solná jeskyně",
    outputAddress: "Čáslavská 28401, Karlov, 284 01 Kutná Hora",
    outputDescription: "Klima prosycené minerály je podobné tomu přímořskému, jen k němu nemusíte cestovat přes půlku Evropy.",
  },
  {
    name: "Zrcadlové bludiště",
    tag: ["relax", "fun", "kids"],
    latitude: 49.949538,
    longitude: 15.266918,
    outputName: "Zrcadlové bludiště",
    outputAddress: "Šultysova 170/8, Vnitřní Město, 284 01 Kutná Hora",
    outputDescription: "Najdete zde zrcadlové bludiště s 80 zrcadly, křišťálové-skleněné bludiště se 150 zrcadly a čirými skly, dětské bludiště (do výšky 120 cm) se 40 zrcadly. ",
  },
  {
    name: "Muzeum Tabáku",
    tag: ["museum", "fun"],
    latitude: 49.960228,
    longitude: 15.290115,
    outputName: "Muzeum Tabáku",
    outputAddress: "Vítězná 1, 284 03 Kutna Hora",
    outputDescription: "Zajímavá je velká sbírka starých krabiček cigaret, které se v Kutné Hoře vyráběly i celé portfolio společnosti.",
  },
]